memory pair game
kottans/frontend-2019-p2p pull request #198
Opened 2022-07-20 11:55 UTC by DaniaB24

###memory pair game

[Demo](https://daniab24.github.io/memory-pair-game/) |
[Code base](https://github.com/DaniaB24/memory-pair-game)

The code is submitted in its own sub-directory and in a dedicated feature branch.
Please, review.

2022-07-24 10:59 UTC, OleksiyRudenko commented
Please keep only files required for the code review (i.e. codebase part that was authored by you).
See section B123 of [submission guidelines](https://github.com/kottans/frontend-2022-homeworks/blob/main/README.md). This helps reviewers jump straight to their job and makes their life easier.

2022-08-17 09:44 UTC, DaniaB24 commented
> Please keep only files required for the code review (i.e. codebase part that was authored by you). See section B123 of [submission guidelines](https://github.com/kottans/frontend-2022-homeworks/blob/main/README.md). This helps reviewers jump straight to their job and makes their life easier.

Hi^ sorry, okey I will remove)

2022-08-17 12:43 UTC, OleksiyRudenko commented
Quite unexpected UX, esp. closer to the end of game.
Also doesn't reshuffle cards for the next game.
![Record_2022_08_17_14_37_34_731-xs](https://user-images.githubusercontent.com/8686631/185130452-5a387bd0-bfeb-40e7-a95a-df70287cb879.gif)

2022-08-17 19:42 UTC, DaniaB24 commented
> Quite unexpected UX, esp. closer to the end of game.
> Also doesn't reshuffle cards for the next game.
> ![Record_2022_08_17_14_37_34_731-xs](https://user-images.githubusercontent.com/8686631/185130452-5a387bd0-bfeb-40e7-a95a-df70287cb879.gif)

okey, I will do it^ thanks for the review <3

2022-08-18 16:07 UTC, OleksiyRudenko commented
Hwo about posting a link in the students' chat and collecting user feedback?

2022-08-18 16:59 UTC, DaniaB24 commented
> Looks visually nice.
> How about posting a link in the students' chat and collecting user feedback?

okey, thanks a lot

2022-08-22 08:26 UTC, OleksiyRudenko commented
This PR contains code from different tasks. Need to fix this

2022-08-24 14:34 UTC, DaniaB24 commented
> This PR contains code from different tasks. Need to fix this

yeah... I did it

2022-08-26 18:41 UTC, OleksiyRudenko commented
Which files do we review?

![image](https://user-images.githubusercontent.com/8686631/186970794-1ae7c4f2-7b10-4c99-8faf-16960974d70b.png)

2022-08-30 13:36 UTC, DaniaB24 commented
> Which [files](https://github.com/kottans/frontend-2019-p2p/pull/198/files) do we review?
> 
> ![image](https://user-images.githubusercontent.com/8686631/186970794-1ae7c4f2-7b10-4c99-8faf-16960974d70b.png)

@OleksiyRudenko  re-review pls:)  i think now everything is clear^

2022-09-04 17:01 UTC, DaniaB24 commented
@OleksiyRudenko

2022-09-08 17:57 UTC, DaniaB24 commented
@OleksiyRudenko  re-review please) thank you a lot

2022-09-13 17:12 UTC, DaniaB24 commented
@OleksiyRudenko

2022-09-15 22:12 UTC, lysenko-sergey-developer requested changes

2022-09-15 22:12 UTC, lysenko-sergey-developer commented on submissions/DaniaB24/memory-pair-game/js/app.js
> +const memoryCards = [...allPlayerCard, ...allPlayerCard];
Move this var next to other vars.

2022-09-15 22:12 UTC, lysenko-sergey-developer commented on submissions/DaniaB24/memory-pair-game/js/app.js
> +createCard();
Move init function to the bottom of file.

2022-09-15 22:12 UTC, lysenko-sergey-developer commented on submissions/DaniaB24/memory-pair-game/js/app.js
> +function createCard() {
Looks like it is not about one card, it is about one card deck.

2022-09-15 22:12 UTC, lysenko-sergey-developer commented on submissions/DaniaB24/memory-pair-game/js/app.js
> +  let clonedCard = memoryCards.map((item) => {
Should be plural. And why do you use let here?

2022-09-15 22:12 UTC, lysenko-sergey-developer commented on submissions/DaniaB24/memory-pair-game/js/app.js
> +      disableCard();
Check your editor config. You should see redundant tab/spaces/empty lines.

2022-09-15 22:12 UTC, lysenko-sergey-developer commented on submissions/DaniaB24/memory-pair-game/js/app.js
> +    firstCard = "";
Resetting to null will be better.

2022-09-15 22:13 UTC, lysenko-sergey-developer commented
@DaniaB24 Good work!👍

2022-09-16 08:21 UTC, DaniaB24 commented
> @DaniaB24 Good work!👍

thank you a lot for review 🤝🤗 I will do it🫡

2022-09-27 21:31 UTC, DaniaB24 commented
@lysenko-sergey-developer @OleksiyRudenko friendly reminder

2022-09-28 19:11 UTC, merged

2022-09-29 14:05 UTC, DaniaB24 commented
@OleksiyRudenko  @lysenko-sergey-developer  thanks a lot<333

2022-09-29 14:10 UTC, OleksiyRudenko commented
@DaniaB24 looks like you are missing only submission for [OOP Exercise](https://github.com/kottans/frontend/blob/master/tasks/js-post-oop.md) to have the full house of tasks.

2022-09-29 15:33 UTC, DaniaB24 commented
> @DaniaB24 looks like you are missing only submission for [OOP Exercise](https://github.com/kottans/frontend/blob/master/tasks/js-post-oop.md) to have the full house of tasks.

https://github.com/kottans/frontend-2022-homeworks/pull/172
it seems to be here

2022-09-29 16:17 UTC, OleksiyRudenko commented
> [kottans/frontend-2022-homeworks#172](https://github.com/kottans/frontend-2022-homeworks/pull/172) it seems to be here

That PR covers [Building a Tiny JS World](https://github.com/kottans/frontend/blob/master/tasks/js-pre-oop.md)

2022-09-29 19:02 UTC, DaniaB24 commented
> > [kottans/frontend-2022-homeworks#172](https://github.com/kottans/frontend-2022-homeworks/pull/172) it seems to be here
> 
> That PR covers [Building a Tiny JS World](https://github.com/kottans/frontend/blob/master/tasks/js-pre-oop.md)

![image](https://user-images.githubusercontent.com/72555333/193119466-9e25a999-b7a4-4c57-8eeb-a0d3ec0064cc.png)
but there is a code for oop 🤦‍♂️

2022-09-29 19:03 UTC, DaniaB24 commented
> > [kottans/frontend-2022-homeworks#172](https://github.com/kottans/frontend-2022-homeworks/pull/172) it seems to be here
> 
> That PR covers [Building a Tiny JS World](https://github.com/kottans/frontend/blob/master/tasks/js-pre-oop.md)



> > > [kottans/frontend-2022-homeworks#172](https://github.com/kottans/frontend-2022-homeworks/pull/172) it seems to be here
> > 
> > 
> > That PR covers [Building a Tiny JS World](https://github.com/kottans/frontend/blob/master/tasks/js-pre-oop.md)
> 
> ![image](https://user-images.githubusercontent.com/72555333/193119466-9e25a999-b7a4-4c57-8eeb-a0d3ec0064cc.png) but there is a code for oop 🤦‍♂️

sorry, my bad